# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('creationTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(b'initiated', b'initiated'), (b'running', b'running'), (b'active', b'active'), (b'complete', b'complete'), (b'terminated', b'terminated'), (b'suspended', b'suspended')], default=b'initiated', max_length=10)),
                ('old_status', models.CharField(blank=True, choices=[(b'initiated', b'initiated'), (b'running', b'running'), (b'active', b'active'), (b'complete', b'complete'), (b'terminated', b'terminated'), (b'suspended', b'suspended')], max_length=10, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('blocked', models.BooleanField(default=False)),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[(b'blocked', b'blocked'), (b'inactive', b'inactive'), (b'active', b'active'), (b'suspended', b'suspended'), (b'fallout', b'fallout'), (b'complete', b'complete')], default=b'inactive', max_length=10)),
            ],
            options={
                'permissions': (('can_change_priority', 'Can change priority'),),
            },
        ),
    ]
