# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 09:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[(b'standard', b'standard'), (b'dummy', b'dummy'), (b'subflow', b'subflow')], default=b'standard', max_length=10, verbose_name=b'type')),
                ('pushapp_param', models.CharField(blank=True, help_text=b"parameters dictionary; example: {'username':'john'}", max_length=100, null=True)),
                ('app_param', models.CharField(blank=True, help_text=b'parameters dictionary', max_length=100, null=True, verbose_name=b'parameters')),
                ('description', models.TextField(blank=True, null=True)),
                ('autostart', models.BooleanField(default=False)),
                ('autofinish', models.BooleanField(default=True)),
                ('join_mode', models.CharField(choices=[(b'and', b'and'), (b'xor', b'xor')], default=b'xor', max_length=3, verbose_name=b'join mode')),
                ('split_mode', models.CharField(choices=[(b'and', b'and'), (b'xor', b'xor')], default=b'and', max_length=3, verbose_name=b'split mode')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text=b'relative to prefix in settings.WF_APPS_PREFIX', max_length=255, unique=True)),
                ('suffix', models.CharField(blank=True, choices=[(b'w', b'workitem.id'), (b'i', b'instance.id'), (b'o', b'object.id')], default=b'w', help_text=b'http://[host]/[settings.WF_APPS_PREFIX/][url]/[suffix]', max_length=1, null=True, verbose_name=b'suffix')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('begin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bprocess', to='workflow.Activity', verbose_name=b'initial activity')),
                ('end', models.ForeignKey(blank=True, help_text=b'a default end activity will be created if blank', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eprocess', to='workflow.Activity', verbose_name=b'final activity')),
            ],
            options={
                'verbose_name_plural': 'Processes',
                'permissions': (('can_instantiate', 'Can instantiate'), ('can_browse', 'Can browse')),
            },
        ),
        migrations.CreateModel(
            name='PushApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(blank=True, help_text=b'ex: instance.condition=="OK" | OK', max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('precondition', models.SlugField(blank=True, help_text=b'object method that return True if transition is posible', null=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_inputs', to='workflow.Activity')),
                ('output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_outputs', to='workflow.Activity')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='workflow.Process')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_host', models.CharField(default=b'localhost:8000', max_length=100)),
                ('notified', models.BooleanField(default=True, verbose_name=b'notification by email')),
                ('last_notif', models.DateTimeField(default=datetime.datetime(2017, 9, 1, 17, 27, 15, 878000))),
                ('nb_wi_notif', models.IntegerField(default=1, help_text=b'notification if the number of items waiting is reached', verbose_name=b'items before notification')),
                ('notif_delay', models.IntegerField(default=1, help_text=b'in days', verbose_name=b'Notification delay')),
                ('urgent_priority', models.IntegerField(default=5, help_text=b'a mail notification is sent when an item has at least this priority level', verbose_name=b'Urgent priority threshold')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Workflow user profile',
                'verbose_name_plural': 'Workflow users profiles',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='application',
            field=models.ForeignKey(blank=True, help_text=b'leave it blank for prototyping the process without coding', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.Application'),
        ),
        migrations.AddField(
            model_name='activity',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.Process'),
        ),
        migrations.AddField(
            model_name='activity',
            name='push_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='push_activities', to='workflow.PushApplication'),
        ),
        migrations.AddField(
            model_name='activity',
            name='roles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_activities', to='workflow.Process'),
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together=set([('title', 'process')]),
        ),
    ]
